# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'testPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # MSaas主包
  pod 'MSaas'

  # 以下按需导入
  # 穿山甲广告主适配包
  pod 'SFAdPangolinAdapter'
  # Gromore广告主适配包
  pod 'SFAdGromoreAdapter'
  # 广点通广告主适配包
  pod 'SFAdGdtAdapter'
  # 快手广告主适配包
  pod 'SFAdKsAdapter'
  # 京准通广告主适配包
  pod 'SFAdJztAdapter'
  # 百度广告主适配包
  pod 'SFAdBaiduAdapter'
  # sigmob广告主适配包
  pod 'SFAdSigmobAdapter'
  # Mintegral广告主适配包
  pod 'SFAdMtgAdapter'

end
